# Generated by Django 4.0.4 on 2022-05-21 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_salary', models.IntegerField(default=0)),
                ('category_name', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name_plural': '1. Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=60)),
                ('client_address', models.CharField(max_length=80)),
                ('client_business', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': '5. Clients',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_sign_time', models.DateField(blank=True, null=True)),
                ('contract_end_time', models.DateField(blank=True, null=True)),
                ('contract_info', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '7. Contracts',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '2. Departments',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': '3. Equipment',
            },
        ),
        migrations.CreateModel(
            name='GroupsEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_start_date', models.DateField(blank=True, null=True)),
                ('signed_end_date', models.DateField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.equipment')),
            ],
            options={
                'verbose_name_plural': '4-1. Groups Equipment',
            },
        ),
        migrations.CreateModel(
            name='GroupsProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_of_work', models.DateField(blank=True, null=True)),
                ('end_of_work', models.DateField(blank=True, null=True)),
                ('work_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '4-3. Groups Projects',
            },
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcontractor_info', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '8. Subcontractors',
            },
        ),
        migrations.CreateModel(
            name='TheGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=80)),
                ('assigned_equipment', models.ManyToManyField(through='organization.GroupsEquipment', to='organization.equipment')),
            ],
            options={
                'verbose_name_plural': '4. Groups',
            },
        ),
        migrations.CreateModel(
            name='TheLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_name', models.CharField(max_length=60)),
                ('chief_age', models.IntegerField(blank=True, null=True)),
                ('chief_address', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': '2-1. TheLead',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=60)),
                ('worker_age', models.IntegerField(blank=True, null=True)),
                ('worker_address', models.CharField(max_length=80)),
                ('assigned_departments', models.ManyToManyField(to='organization.department')),
            ],
            options={
                'verbose_name_plural': '0. Workers',
            },
        ),
        migrations.CreateModel(
            name='WorkersGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('dismissal_date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.thegroup')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.worker')),
            ],
            options={
                'verbose_name_plural': '4-0. Groups Workers',
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='assigned_groups',
            field=models.ManyToManyField(through='organization.WorkersGroups', to='organization.thegroup'),
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_category',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.category'),
        ),
        migrations.CreateModel(
            name='TechniqueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_instruments', models.CharField(max_length=80)),
                ('serviced_equipment', models.CharField(max_length=120)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.worker')),
            ],
            options={
                'verbose_name_plural': '1-3. Technique Category',
            },
        ),
        migrations.CreateModel(
            name='ServiceStaffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_zone', models.CharField(max_length=60)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.worker')),
            ],
            options={
                'verbose_name_plural': '1-5. Service Staff Category',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_sign_time', models.DateField(blank=True, null=True)),
                ('project_end_time', models.DateField(blank=True, null=True)),
                ('project_price', models.IntegerField()),
                ('project_info', models.CharField(max_length=255)),
                ('assigned_groups', models.ManyToManyField(through='organization.GroupsProjects', to='organization.thegroup')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.worker')),
            ],
            options={
                'verbose_name_plural': '6. Projects',
            },
        ),
        migrations.CreateModel(
            name='LabAssistantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_lab', models.CharField(max_length=60)),
                ('assigned_inventory', models.CharField(max_length=120)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.worker')),
            ],
            options={
                'verbose_name_plural': '1-4. Lab Assistant Category',
            },
        ),
        migrations.AddField(
            model_name='groupsprojects',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.thegroup'),
        ),
        migrations.AddField(
            model_name='groupsprojects',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.project'),
        ),
        migrations.AddField(
            model_name='groupsprojects',
            name='subcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.subcontractor'),
        ),
        migrations.AddField(
            model_name='groupsequipment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.thegroup'),
        ),
        migrations.CreateModel(
            name='GroupsContracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_of_work', models.DateField(blank=True, null=True)),
                ('end_of_work', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.contract')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.thegroup')),
            ],
            options={
                'verbose_name_plural': '4-2. Groups Contracts',
            },
        ),
        migrations.CreateModel(
            name='EquipmentInDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('unsigned_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.equipment')),
            ],
            options={
                'verbose_name_plural': '3-1. Equipment In Departments',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='assigned_departments',
            field=models.ManyToManyField(through='organization.EquipmentInDepartments', to='organization.department'),
        ),
        migrations.CreateModel(
            name='EngineerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.worker')),
            ],
            options={
                'verbose_name_plural': '1-1. Engineer Category',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.thelead'),
        ),
        migrations.CreateModel(
            name='ContractsProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.contract')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.project')),
            ],
            options={
                'verbose_name_plural': '7-1. Contracts Projects',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='assigned_groups',
            field=models.ManyToManyField(through='organization.GroupsContracts', to='organization.thegroup'),
        ),
        migrations.AddField(
            model_name='contract',
            name='assigned_projects',
            field=models.ManyToManyField(through='organization.ContractsProjects', to='organization.project'),
        ),
        migrations.AddField(
            model_name='contract',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.worker'),
        ),
        migrations.CreateModel(
            name='ConstructorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificates_number', models.IntegerField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.worker')),
            ],
            options={
                'verbose_name_plural': '1-2. Constructor Category',
            },
        ),
        migrations.CreateModel(
            name='ClientsContracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.contract')),
            ],
            options={
                'verbose_name_plural': '5-1. Clients Contracts',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_contracts',
            field=models.ManyToManyField(through='organization.ClientsContracts', to='organization.contract'),
        ),
    ]
